repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args:
          - detect
          - --no-banner
          - --redact
          - --config=.gitleaks.toml

